{% set name = "h11" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e35b956cf45792e4caa5885e69fba00bdbc6ffafbfa020300e549b208ee5ff1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - h11

about:
  home: https://github.com/python-hyper/h11
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A pure-Python HTTP/1.1 protocol library.
  description: |
    h11 is an HTTP/1.1 protocol library written in Python, heavily inspired by
    [hyper-h2](https://hyper-h2.readthedocs.io/en/stable/).
  doc_url: https://h11.readthedocs.io/en/latest/
  dev_url: https://github.com/python-hyper/h11

extra:
  recipe-maintainers:
    - carlodri
